### ISSUE TITLE
[BUG] Searching for games with special characters, for example the + leads to less optimal results

### ISSUE THREAD

**Issue by CasperH2O** [craftersmine/SteamGridDB.NET#12]
**Describe the bug**
Searching for apps that contain special characters, for example with a + for Notepad++ leads to not getting search results back that even include Notepad++

**To Reproduce**

When I search the steamgriddb website for "Notepad++" I see the application I expect (Notepad++ (2003)) as the top result.

However, using the library, when searching for:
"Notepad", I get 3 results:

Windows Notepad (Program)
Notepad++
Notepadqq (Program)

"Notepad++", I get 1 result, which is the wrong one:

Windows Notepad (Program)

I could first subtract odd characters from my initial search and then do a fuzzy matching on the results for the actual name (including ++) but I'm a bit stumped it does not return what I expect initially, searching for the actual program name in the first place.

Searching for the following:

`Notepad%2B%2B` returns classic notepad (1 result)
`Notepad%252B%252B` returns 3 results, with the expected Notepad++ at the top

As a workaround, together with Zennn from the SteamGridDB API, we found that URL encoding twice leads to the expected result. This C# code is sufficient:

```
                string originalString = appl.ApplicationName;
                string encodedString = HttpUtility.UrlEncode(appl.ApplicationName);
                string encodedencodedString = HttpUtility.UrlEncode(encodedString);

                var gameSearchResults = await steamGridDb.SearchForGamesAsync(encodedencodedString).ConfigureAwait(false);
```

**Comment by craftersmine** [comment]
For some reason, SteamGridDB server only accepts the double-encoded variant, even Insomnia fails the first encoding, and only returns "Windows Notepad" result.

Single encoded variant:
![image](https://github.com/user-attachments/assets/599d643d-7573-46d1-b9f1-344cf4b63f42)

Double encoded variant:
![image](https://github.com/user-attachments/assets/d2e2db87-dbf6-42ca-813d-f68cf3b92d6b)

**Comment by craftersmine** [comment]
Unfortunatelly, I don't think there is any fixes possible, other than double-encoding search term like this:
```csharp
public async Task<SteamGridDbGame[]> SearchForGamesAsync(string searchTerm)
{
    searchTerm = Uri.EscapeDataString(Uri.EscapeDataString(searchTerm));
    var response = await Get($"search/autocomplete/{searchTerm}");
    if (response.Data != null) return response.Data.ToObject<SteamGridDbGame[]>();
    return null;
}
```

So, I'll make changes to the library and update the library
